sudo: required

language: cpp

services:
  - docker

before_install:
- docker info
- docker pull insighttoolkit/minimalpathextraction-test

script:
- mkdir ../itkSuperPixel-build
- pwd
- ls
- docker run -v ./:/usr/src/itkSuperPixel -v ../itkSuperPixel-build:/usr/src/itkSuperPixel-build insighttoolkit/minimalpathextraction-test /usr/src/itkSuperPixel/test/Docker/test.sh

